// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/entities/app_setting.dart';
import 'model/entities/category.dart';
import 'model/entities/component.dart';
import 'model/entities/component_option.dart';
import 'model/entities/component_type.dart';
import 'model/entities/price_record.dart';
import 'model/entities/project.dart';
import 'model/entities/project_item.dart';
import 'model/entities/project_option.dart';
import 'model/entities/stock_item.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 735688662067852918),
    name: 'Category',
    lastPropertyId: const obx_int.IdUid(8, 3401959104311952641),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8838519174728974467),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6716892446646810134),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5239876977356516614),
        name: 'colorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1956916245923038936),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7488939032776671371),
        name: 'iconSvg',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3401959104311952641),
        name: 'keywords',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'component',
        srcEntity: 'Component',
        srcField: 'category',
      ),
      obx_int.ModelBacklink(
        name: 'types',
        srcEntity: 'ComponentType',
        srcField: 'category',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7432719125809346356),
    name: 'Component',
    lastPropertyId: const obx_int.IdUid(9, 6470763746805232297),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7873598098431675365),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3634271832066945026),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1915175074799785345),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1024023797232900842),
        name: 'base64Image',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6916872785050517054),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 267711657199906249),
        relationField: 'category',
        relationTarget: 'Category',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5047079502958179936),
        name: 'iconSvg',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4143022919974005364),
        name: 'typeId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(11, 8401913787042663121),
        relationField: 'type',
        relationTarget: 'ComponentType',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8049393948878961576),
        name: 'attributesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6470763746805232297),
        name: 'lowStockThreshold',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'options',
        srcEntity: 'ComponentOption',
        srcField: 'component',
      ),
      obx_int.ModelBacklink(
        name: 'projectItem',
        srcEntity: 'ProjectItem',
        srcField: 'component',
      ),
      obx_int.ModelBacklink(
        name: 'stockItems',
        srcEntity: 'StockItem',
        srcField: 'component',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6081016848382265369),
    name: 'ComponentOption',
    lastPropertyId: const obx_int.IdUid(9, 8416046497509526526),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3353291662892062929),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6390919814860314811),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 49313635525721526),
        name: 'unitsPerPack',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5973240023728994270),
        name: 'pricePerPack',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5092400232993980417),
        name: 'componentId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 5562498534427402224),
        relationField: 'component',
        relationTarget: 'Component',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 398871174802654785),
        name: 'link',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5021700049413886572),
        name: 'shop',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2329143711318660867),
        name: 'availabilityJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8416046497509526526),
        name: 'priceCheckedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'projectItem',
        srcEntity: 'ProjectItem',
        srcField: 'componentOption',
      ),
      obx_int.ModelBacklink(
        name: 'priceHistory',
        srcEntity: 'PriceRecord',
        srcField: 'option',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 4547103194667605335),
    name: 'ProjectItem',
    lastPropertyId: const obx_int.IdUid(9, 8611361039882395797),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7198949110572192655),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 877014537199689448),
        name: 'quantity',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 150656000289696912),
        name: 'componentId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 7914224584363898835),
        relationField: 'component',
        relationTarget: 'Component',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1956453245173252739),
        name: 'componentOptionId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(6, 6573140737730838987),
        relationField: 'componentOption',
        relationTarget: 'ComponentOption',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4349058352890504777),
        name: 'projectOptionId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(7, 2460496800844713591),
        relationField: 'projectOption',
        relationTarget: 'ProjectOption',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7113912605860092562),
        name: 'projectId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(8, 5632878586015758333),
        relationField: 'project',
        relationTarget: 'Project',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8611361039882395797),
        name: 'variantJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 371008579262511988),
    name: 'ProjectOption',
    lastPropertyId: const obx_int.IdUid(5, 8716145627210334296),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1501010626906604339),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8076127869418753446),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5654727925094684581),
        name: 'projectId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(9, 3612696205726049625),
        relationField: 'project',
        relationTarget: 'Project',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8716145627210334296),
        name: 'description',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'items',
        srcEntity: 'ProjectItem',
        srcField: 'projectOption',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 8436796991232977367),
    name: 'Project',
    lastPropertyId: const obx_int.IdUid(6, 8673916435767158666),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7550198771448469810),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3772008035074211062),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9074943017746042346),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4015687585516383975),
        name: 'base64Image',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1697388478925904541),
        name: 'updatedAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8673916435767158666),
        name: 'status',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'baseItems',
        srcEntity: 'ProjectItem',
        srcField: 'project',
      ),
      obx_int.ModelBacklink(
        name: 'projectOptions',
        srcEntity: 'ProjectOption',
        srcField: 'project',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 2461670290478599242),
    name: 'AppSetting',
    lastPropertyId: const obx_int.IdUid(3, 9185106354010141510),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6613349224083590676),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4839894064081357779),
        name: 'key',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(10, 4965281240800076624),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9185106354010141510),
        name: 'value',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 8458293193615110203),
    name: 'ComponentType',
    lastPropertyId: const obx_int.IdUid(6, 4574549558319245082),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6292615044406994223),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4589402240433262256),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8866444762521029981),
        name: 'defaultIconSvg',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6408607967043718175),
        name: 'keywords',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1591738434140199287),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(12, 2630929082995307557),
        relationField: 'category',
        relationTarget: 'Category',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4574549558319245082),
        name: 'attributeTemplate',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'components',
        srcEntity: 'Component',
        srcField: 'type',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 4379620560238457725),
    name: 'PriceRecord',
    lastPropertyId: const obx_int.IdUid(5, 5551059736542004289),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 927144323127825951),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8518520353474833988),
        name: 'pricePerPack',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3425243989936641146),
        name: 'unitsPerPack',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3953374987542737624),
        name: 'recordedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5551059736542004289),
        name: 'optionId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(13, 2037780105567517895),
        relationField: 'option',
        relationTarget: 'ComponentOption',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 5463171404995936114),
    name: 'StockItem',
    lastPropertyId: const obx_int.IdUid(5, 3106582597663559547),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6939053514091369802),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2216316790909979240),
        name: 'quantity',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7489157827013620117),
        name: 'location',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4535183218698774380),
        name: 'variantJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3106582597663559547),
        name: 'componentId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(14, 1774872849311144325),
        relationField: 'component',
        relationTarget: 'Component',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(10, 5463171404995936114),
    lastIndexId: const obx_int.IdUid(14, 1774872849311144325),
    lastRelationId: const obx_int.IdUid(2, 2185989689109593573),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [7121405856924190099, 7543092616379739934],
    retiredPropertyUids: const [
      5724160405490332509,
      932998436461860071,
      8919251242098379596,
      1525535272044134410,
      5065092297872908668,
    ],
    retiredRelationUids: const [4042897894924188460, 2185989689109593573],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Category: obx_int.EntityDefinition<Category>(
      model: _entities[0],
      toOneRelations: (Category object) => [],
      toManyRelations: (Category object) => {
        obx_int.RelInfo<Component>.toOneBacklink(
          5,
          object.id,
          (Component srcObject) => srcObject.category,
        ): object.component,
        obx_int.RelInfo<ComponentType>.toOneBacklink(
          5,
          object.id,
          (ComponentType srcObject) => srcObject.category,
        ): object.types,
      },
      getId: (Category object) => object.id,
      setId: (Category object, int id) {
        object.id = id;
      },
      objectToFB: (Category object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final iconSvgOffset = fbb.writeString(object.iconSvg);
        final keywordsOffset = fbb.writeList(
          object.keywords.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(3, object.colorValue);
        fbb.addOffset(5, descriptionOffset);
        fbb.addOffset(6, iconSvgOffset);
        fbb.addOffset(7, keywordsOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final colorValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final iconSvgParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final keywordsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 18, []);
        final object = Category(
          id: idParam,
          name: nameParam,
          description: descriptionParam,
          colorValue: colorValueParam,
          iconSvg: iconSvgParam,
          keywords: keywordsParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<Category>(
          object.component,
          store,
          obx_int.RelInfo<Component>.toOneBacklink(
            5,
            object.id,
            (Component srcObject) => srcObject.category,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Category>(
          object.types,
          store,
          obx_int.RelInfo<ComponentType>.toOneBacklink(
            5,
            object.id,
            (ComponentType srcObject) => srcObject.category,
          ),
        );
        return object;
      },
    ),
    Component: obx_int.EntityDefinition<Component>(
      model: _entities[1],
      toOneRelations: (Component object) => [object.category, object.type],
      toManyRelations: (Component object) => {
        obx_int.RelInfo<ComponentOption>.toOneBacklink(
          5,
          object.id,
          (ComponentOption srcObject) => srcObject.component,
        ): object.options,
        obx_int.RelInfo<ProjectItem>.toOneBacklink(
          3,
          object.id,
          (ProjectItem srcObject) => srcObject.component,
        ): object.projectItem,
        obx_int.RelInfo<StockItem>.toOneBacklink(
          5,
          object.id,
          (StockItem srcObject) => srcObject.component,
        ): object.stockItems,
      },
      getId: (Component object) => object.id,
      setId: (Component object, int id) {
        object.id = id;
      },
      objectToFB: (Component object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final base64ImageOffset = fbb.writeString(object.base64Image);
        final iconSvgOffset = fbb.writeString(object.iconSvg);
        final attributesJsonOffset = fbb.writeString(object.attributesJson);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, base64ImageOffset);
        fbb.addInt64(4, object.category.targetId);
        fbb.addOffset(5, iconSvgOffset);
        fbb.addInt64(6, object.type.targetId);
        fbb.addOffset(7, attributesJsonOffset);
        fbb.addInt64(8, object.lowStockThreshold);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final base64ImageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final iconSvgParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final attributesJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final lowStockThresholdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final object = Component(
          id: idParam,
          name: nameParam,
          description: descriptionParam,
          base64Image: base64ImageParam,
          iconSvg: iconSvgParam,
          attributesJson: attributesJsonParam,
          lowStockThreshold: lowStockThresholdParam,
        );
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.category.attach(store);
        object.type.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.type.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Component>(
          object.options,
          store,
          obx_int.RelInfo<ComponentOption>.toOneBacklink(
            5,
            object.id,
            (ComponentOption srcObject) => srcObject.component,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Component>(
          object.projectItem,
          store,
          obx_int.RelInfo<ProjectItem>.toOneBacklink(
            3,
            object.id,
            (ProjectItem srcObject) => srcObject.component,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Component>(
          object.stockItems,
          store,
          obx_int.RelInfo<StockItem>.toOneBacklink(
            5,
            object.id,
            (StockItem srcObject) => srcObject.component,
          ),
        );
        return object;
      },
    ),
    ComponentOption: obx_int.EntityDefinition<ComponentOption>(
      model: _entities[2],
      toOneRelations: (ComponentOption object) => [object.component],
      toManyRelations: (ComponentOption object) => {
        obx_int.RelInfo<ProjectItem>.toOneBacklink(
          6,
          object.id,
          (ProjectItem srcObject) => srcObject.componentOption,
        ): object.projectItem,
        obx_int.RelInfo<PriceRecord>.toOneBacklink(
          5,
          object.id,
          (PriceRecord srcObject) => srcObject.option,
        ): object.priceHistory,
      },
      getId: (ComponentOption object) => object.id,
      setId: (ComponentOption object, int id) {
        object.id = id;
      },
      objectToFB: (ComponentOption object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final linkOffset = fbb.writeString(object.link);
        final shopOffset = fbb.writeString(object.shop);
        final availabilityJsonOffset = fbb.writeString(object.availabilityJson);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.unitsPerPack);
        fbb.addInt64(3, object.pricePerPack);
        fbb.addInt64(4, object.component.targetId);
        fbb.addOffset(5, linkOffset);
        fbb.addOffset(6, shopOffset);
        fbb.addOffset(7, availabilityJsonOffset);
        fbb.addInt64(8, object.priceCheckedAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final priceCheckedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final unitsPerPackParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final pricePerPackParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final linkParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final shopParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final availabilityJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final priceCheckedAtParam = priceCheckedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(priceCheckedAtValue);
        final object = ComponentOption(
          id: idParam,
          name: nameParam,
          unitsPerPack: unitsPerPackParam,
          pricePerPack: pricePerPackParam,
          link: linkParam,
          shop: shopParam,
          availabilityJson: availabilityJsonParam,
          priceCheckedAt: priceCheckedAtParam,
        );
        object.component.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.component.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<ComponentOption>(
          object.projectItem,
          store,
          obx_int.RelInfo<ProjectItem>.toOneBacklink(
            6,
            object.id,
            (ProjectItem srcObject) => srcObject.componentOption,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<ComponentOption>(
          object.priceHistory,
          store,
          obx_int.RelInfo<PriceRecord>.toOneBacklink(
            5,
            object.id,
            (PriceRecord srcObject) => srcObject.option,
          ),
        );
        return object;
      },
    ),
    ProjectItem: obx_int.EntityDefinition<ProjectItem>(
      model: _entities[3],
      toOneRelations: (ProjectItem object) => [
        object.component,
        object.componentOption,
        object.projectOption,
        object.project,
      ],
      toManyRelations: (ProjectItem object) => {},
      getId: (ProjectItem object) => object.id,
      setId: (ProjectItem object, int id) {
        object.id = id;
      },
      objectToFB: (ProjectItem object, fb.Builder fbb) {
        final variantJsonOffset = fbb.writeString(object.variantJson);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.quantity);
        fbb.addInt64(2, object.component.targetId);
        fbb.addInt64(5, object.componentOption.targetId);
        fbb.addInt64(6, object.projectOption.targetId);
        fbb.addInt64(7, object.project.targetId);
        fbb.addOffset(8, variantJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final quantityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final variantJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final object = ProjectItem(
          id: idParam,
          quantity: quantityParam,
          variantJson: variantJsonParam,
        );
        object.component.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.component.attach(store);
        object.componentOption.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        object.componentOption.attach(store);
        object.projectOption.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.projectOption.attach(store);
        object.project.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        object.project.attach(store);
        return object;
      },
    ),
    ProjectOption: obx_int.EntityDefinition<ProjectOption>(
      model: _entities[4],
      toOneRelations: (ProjectOption object) => [object.project],
      toManyRelations: (ProjectOption object) => {
        obx_int.RelInfo<ProjectItem>.toOneBacklink(
          7,
          object.id,
          (ProjectItem srcObject) => srcObject.projectOption,
        ): object.items,
      },
      getId: (ProjectOption object) => object.id,
      setId: (ProjectOption object, int id) {
        object.id = id;
      },
      objectToFB: (ProjectOption object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.project.targetId);
        fbb.addOffset(4, descriptionOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = ProjectOption(
          id: idParam,
          name: nameParam,
          description: descriptionParam,
        );
        object.project.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.project.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<ProjectOption>(
          object.items,
          store,
          obx_int.RelInfo<ProjectItem>.toOneBacklink(
            7,
            object.id,
            (ProjectItem srcObject) => srcObject.projectOption,
          ),
        );
        return object;
      },
    ),
    Project: obx_int.EntityDefinition<Project>(
      model: _entities[5],
      toOneRelations: (Project object) => [],
      toManyRelations: (Project object) => {
        obx_int.RelInfo<ProjectItem>.toOneBacklink(
          8,
          object.id,
          (ProjectItem srcObject) => srcObject.project,
        ): object.baseItems,
        obx_int.RelInfo<ProjectOption>.toOneBacklink(
          3,
          object.id,
          (ProjectOption srcObject) => srcObject.project,
        ): object.projectOptions,
      },
      getId: (Project object) => object.id,
      setId: (Project object, int id) {
        object.id = id;
      },
      objectToFB: (Project object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final base64ImageOffset = fbb.writeString(object.base64Image);
        final statusOffset = fbb.writeString(object.status);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, base64ImageOffset);
        fbb.addInt64(4, object.updatedAt);
        fbb.addOffset(5, statusOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final base64ImageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final updatedAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = Project(
          id: idParam,
          name: nameParam,
          description: descriptionParam,
          base64Image: base64ImageParam,
          updatedAt: updatedAtParam,
          status: statusParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<Project>(
          object.baseItems,
          store,
          obx_int.RelInfo<ProjectItem>.toOneBacklink(
            8,
            object.id,
            (ProjectItem srcObject) => srcObject.project,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Project>(
          object.projectOptions,
          store,
          obx_int.RelInfo<ProjectOption>.toOneBacklink(
            3,
            object.id,
            (ProjectOption srcObject) => srcObject.project,
          ),
        );
        return object;
      },
    ),
    AppSetting: obx_int.EntityDefinition<AppSetting>(
      model: _entities[6],
      toOneRelations: (AppSetting object) => [],
      toManyRelations: (AppSetting object) => {},
      getId: (AppSetting object) => object.id,
      setId: (AppSetting object, int id) {
        object.id = id;
      },
      objectToFB: (AppSetting object, fb.Builder fbb) {
        final keyOffset = fbb.writeString(object.key);
        final valueOffset = fbb.writeString(object.value);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, keyOffset);
        fbb.addOffset(2, valueOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final keyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final valueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = AppSetting(
          id: idParam,
          key: keyParam,
          value: valueParam,
        );

        return object;
      },
    ),
    ComponentType: obx_int.EntityDefinition<ComponentType>(
      model: _entities[7],
      toOneRelations: (ComponentType object) => [object.category],
      toManyRelations: (ComponentType object) => {
        obx_int.RelInfo<Component>.toOneBacklink(
          7,
          object.id,
          (Component srcObject) => srcObject.type,
        ): object.components,
      },
      getId: (ComponentType object) => object.id,
      setId: (ComponentType object, int id) {
        object.id = id;
      },
      objectToFB: (ComponentType object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final defaultIconSvgOffset = fbb.writeString(object.defaultIconSvg);
        final keywordsOffset = fbb.writeList(
          object.keywords.map(fbb.writeString).toList(growable: false),
        );
        final attributeTemplateOffset = fbb.writeList(
          object.attributeTemplate.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, defaultIconSvgOffset);
        fbb.addOffset(3, keywordsOffset);
        fbb.addInt64(4, object.category.targetId);
        fbb.addOffset(5, attributeTemplateOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final defaultIconSvgParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final keywordsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 10, []);
        final attributeTemplateParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 14, []);
        final object = ComponentType(
          id: idParam,
          name: nameParam,
          defaultIconSvg: defaultIconSvgParam,
          keywords: keywordsParam,
          attributeTemplate: attributeTemplateParam,
        );
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.category.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<ComponentType>(
          object.components,
          store,
          obx_int.RelInfo<Component>.toOneBacklink(
            7,
            object.id,
            (Component srcObject) => srcObject.type,
          ),
        );
        return object;
      },
    ),
    PriceRecord: obx_int.EntityDefinition<PriceRecord>(
      model: _entities[8],
      toOneRelations: (PriceRecord object) => [object.option],
      toManyRelations: (PriceRecord object) => {},
      getId: (PriceRecord object) => object.id,
      setId: (PriceRecord object, int id) {
        object.id = id;
      },
      objectToFB: (PriceRecord object, fb.Builder fbb) {
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.pricePerPack);
        fbb.addInt64(2, object.unitsPerPack);
        fbb.addInt64(3, object.recordedAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.option.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final pricePerPackParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final unitsPerPackParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final recordedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = PriceRecord(
          id: idParam,
          pricePerPack: pricePerPackParam,
          unitsPerPack: unitsPerPackParam,
          recordedAt: recordedAtParam,
        );
        object.option.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.option.attach(store);
        return object;
      },
    ),
    StockItem: obx_int.EntityDefinition<StockItem>(
      model: _entities[9],
      toOneRelations: (StockItem object) => [object.component],
      toManyRelations: (StockItem object) => {},
      getId: (StockItem object) => object.id,
      setId: (StockItem object, int id) {
        object.id = id;
      },
      objectToFB: (StockItem object, fb.Builder fbb) {
        final locationOffset = fbb.writeString(object.location);
        final variantJsonOffset = fbb.writeString(object.variantJson);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.quantity);
        fbb.addOffset(2, locationOffset);
        fbb.addOffset(3, variantJsonOffset);
        fbb.addInt64(4, object.component.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final quantityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final locationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final variantJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = StockItem(
          id: idParam,
          quantity: quantityParam,
          location: locationParam,
          variantJson: variantJsonParam,
        );
        object.component.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.component.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Category] entity fields to define ObjectBox queries.
class Category_ {
  /// See [Category.id].
  static final id = obx.QueryIntegerProperty<Category>(
    _entities[0].properties[0],
  );

  /// See [Category.name].
  static final name = obx.QueryStringProperty<Category>(
    _entities[0].properties[1],
  );

  /// See [Category.colorValue].
  static final colorValue = obx.QueryIntegerProperty<Category>(
    _entities[0].properties[2],
  );

  /// See [Category.description].
  static final description = obx.QueryStringProperty<Category>(
    _entities[0].properties[3],
  );

  /// See [Category.iconSvg].
  static final iconSvg = obx.QueryStringProperty<Category>(
    _entities[0].properties[4],
  );

  /// See [Category.keywords].
  static final keywords = obx.QueryStringVectorProperty<Category>(
    _entities[0].properties[5],
  );

  /// see [Category.component]
  static final component = obx.QueryBacklinkToMany<Component, Category>(
    Component_.category,
  );

  /// see [Category.types]
  static final types = obx.QueryBacklinkToMany<ComponentType, Category>(
    ComponentType_.category,
  );
}

/// [Component] entity fields to define ObjectBox queries.
class Component_ {
  /// See [Component.id].
  static final id = obx.QueryIntegerProperty<Component>(
    _entities[1].properties[0],
  );

  /// See [Component.name].
  static final name = obx.QueryStringProperty<Component>(
    _entities[1].properties[1],
  );

  /// See [Component.description].
  static final description = obx.QueryStringProperty<Component>(
    _entities[1].properties[2],
  );

  /// See [Component.base64Image].
  static final base64Image = obx.QueryStringProperty<Component>(
    _entities[1].properties[3],
  );

  /// See [Component.category].
  static final category = obx.QueryRelationToOne<Component, Category>(
    _entities[1].properties[4],
  );

  /// See [Component.iconSvg].
  static final iconSvg = obx.QueryStringProperty<Component>(
    _entities[1].properties[5],
  );

  /// See [Component.type].
  static final type = obx.QueryRelationToOne<Component, ComponentType>(
    _entities[1].properties[6],
  );

  /// See [Component.attributesJson].
  static final attributesJson = obx.QueryStringProperty<Component>(
    _entities[1].properties[7],
  );

  /// See [Component.lowStockThreshold].
  static final lowStockThreshold = obx.QueryIntegerProperty<Component>(
    _entities[1].properties[8],
  );

  /// see [Component.options]
  static final options = obx.QueryBacklinkToMany<ComponentOption, Component>(
    ComponentOption_.component,
  );

  /// see [Component.projectItem]
  static final projectItem = obx.QueryBacklinkToMany<ProjectItem, Component>(
    ProjectItem_.component,
  );

  /// see [Component.stockItems]
  static final stockItems = obx.QueryBacklinkToMany<StockItem, Component>(
    StockItem_.component,
  );
}

/// [ComponentOption] entity fields to define ObjectBox queries.
class ComponentOption_ {
  /// See [ComponentOption.id].
  static final id = obx.QueryIntegerProperty<ComponentOption>(
    _entities[2].properties[0],
  );

  /// See [ComponentOption.name].
  static final name = obx.QueryStringProperty<ComponentOption>(
    _entities[2].properties[1],
  );

  /// See [ComponentOption.unitsPerPack].
  static final unitsPerPack = obx.QueryIntegerProperty<ComponentOption>(
    _entities[2].properties[2],
  );

  /// See [ComponentOption.pricePerPack].
  static final pricePerPack = obx.QueryIntegerProperty<ComponentOption>(
    _entities[2].properties[3],
  );

  /// See [ComponentOption.component].
  static final component = obx.QueryRelationToOne<ComponentOption, Component>(
    _entities[2].properties[4],
  );

  /// See [ComponentOption.link].
  static final link = obx.QueryStringProperty<ComponentOption>(
    _entities[2].properties[5],
  );

  /// See [ComponentOption.shop].
  static final shop = obx.QueryStringProperty<ComponentOption>(
    _entities[2].properties[6],
  );

  /// See [ComponentOption.availabilityJson].
  static final availabilityJson = obx.QueryStringProperty<ComponentOption>(
    _entities[2].properties[7],
  );

  /// See [ComponentOption.priceCheckedAt].
  static final priceCheckedAt = obx.QueryDateProperty<ComponentOption>(
    _entities[2].properties[8],
  );

  /// see [ComponentOption.projectItem]
  static final projectItem =
      obx.QueryBacklinkToMany<ProjectItem, ComponentOption>(
        ProjectItem_.componentOption,
      );

  /// see [ComponentOption.priceHistory]
  static final priceHistory =
      obx.QueryBacklinkToMany<PriceRecord, ComponentOption>(
        PriceRecord_.option,
      );
}

/// [ProjectItem] entity fields to define ObjectBox queries.
class ProjectItem_ {
  /// See [ProjectItem.id].
  static final id = obx.QueryIntegerProperty<ProjectItem>(
    _entities[3].properties[0],
  );

  /// See [ProjectItem.quantity].
  static final quantity = obx.QueryIntegerProperty<ProjectItem>(
    _entities[3].properties[1],
  );

  /// See [ProjectItem.component].
  static final component = obx.QueryRelationToOne<ProjectItem, Component>(
    _entities[3].properties[2],
  );

  /// See [ProjectItem.componentOption].
  static final componentOption =
      obx.QueryRelationToOne<ProjectItem, ComponentOption>(
        _entities[3].properties[3],
      );

  /// See [ProjectItem.projectOption].
  static final projectOption =
      obx.QueryRelationToOne<ProjectItem, ProjectOption>(
        _entities[3].properties[4],
      );

  /// See [ProjectItem.project].
  static final project = obx.QueryRelationToOne<ProjectItem, Project>(
    _entities[3].properties[5],
  );

  /// See [ProjectItem.variantJson].
  static final variantJson = obx.QueryStringProperty<ProjectItem>(
    _entities[3].properties[6],
  );
}

/// [ProjectOption] entity fields to define ObjectBox queries.
class ProjectOption_ {
  /// See [ProjectOption.id].
  static final id = obx.QueryIntegerProperty<ProjectOption>(
    _entities[4].properties[0],
  );

  /// See [ProjectOption.name].
  static final name = obx.QueryStringProperty<ProjectOption>(
    _entities[4].properties[1],
  );

  /// See [ProjectOption.project].
  static final project = obx.QueryRelationToOne<ProjectOption, Project>(
    _entities[4].properties[2],
  );

  /// See [ProjectOption.description].
  static final description = obx.QueryStringProperty<ProjectOption>(
    _entities[4].properties[3],
  );

  /// see [ProjectOption.items]
  static final items = obx.QueryBacklinkToMany<ProjectItem, ProjectOption>(
    ProjectItem_.projectOption,
  );
}

/// [Project] entity fields to define ObjectBox queries.
class Project_ {
  /// See [Project.id].
  static final id = obx.QueryIntegerProperty<Project>(
    _entities[5].properties[0],
  );

  /// See [Project.name].
  static final name = obx.QueryStringProperty<Project>(
    _entities[5].properties[1],
  );

  /// See [Project.description].
  static final description = obx.QueryStringProperty<Project>(
    _entities[5].properties[2],
  );

  /// See [Project.base64Image].
  static final base64Image = obx.QueryStringProperty<Project>(
    _entities[5].properties[3],
  );

  /// See [Project.updatedAt].
  static final updatedAt = obx.QueryIntegerProperty<Project>(
    _entities[5].properties[4],
  );

  /// See [Project.status].
  static final status = obx.QueryStringProperty<Project>(
    _entities[5].properties[5],
  );

  /// see [Project.baseItems]
  static final baseItems = obx.QueryBacklinkToMany<ProjectItem, Project>(
    ProjectItem_.project,
  );

  /// see [Project.projectOptions]
  static final projectOptions = obx.QueryBacklinkToMany<ProjectOption, Project>(
    ProjectOption_.project,
  );
}

/// [AppSetting] entity fields to define ObjectBox queries.
class AppSetting_ {
  /// See [AppSetting.id].
  static final id = obx.QueryIntegerProperty<AppSetting>(
    _entities[6].properties[0],
  );

  /// See [AppSetting.key].
  static final key = obx.QueryStringProperty<AppSetting>(
    _entities[6].properties[1],
  );

  /// See [AppSetting.value].
  static final value = obx.QueryStringProperty<AppSetting>(
    _entities[6].properties[2],
  );
}

/// [ComponentType] entity fields to define ObjectBox queries.
class ComponentType_ {
  /// See [ComponentType.id].
  static final id = obx.QueryIntegerProperty<ComponentType>(
    _entities[7].properties[0],
  );

  /// See [ComponentType.name].
  static final name = obx.QueryStringProperty<ComponentType>(
    _entities[7].properties[1],
  );

  /// See [ComponentType.defaultIconSvg].
  static final defaultIconSvg = obx.QueryStringProperty<ComponentType>(
    _entities[7].properties[2],
  );

  /// See [ComponentType.keywords].
  static final keywords = obx.QueryStringVectorProperty<ComponentType>(
    _entities[7].properties[3],
  );

  /// See [ComponentType.category].
  static final category = obx.QueryRelationToOne<ComponentType, Category>(
    _entities[7].properties[4],
  );

  /// See [ComponentType.attributeTemplate].
  static final attributeTemplate = obx.QueryStringVectorProperty<ComponentType>(
    _entities[7].properties[5],
  );

  /// see [ComponentType.components]
  static final components = obx.QueryBacklinkToMany<Component, ComponentType>(
    Component_.type,
  );
}

/// [PriceRecord] entity fields to define ObjectBox queries.
class PriceRecord_ {
  /// See [PriceRecord.id].
  static final id = obx.QueryIntegerProperty<PriceRecord>(
    _entities[8].properties[0],
  );

  /// See [PriceRecord.pricePerPack].
  static final pricePerPack = obx.QueryIntegerProperty<PriceRecord>(
    _entities[8].properties[1],
  );

  /// See [PriceRecord.unitsPerPack].
  static final unitsPerPack = obx.QueryIntegerProperty<PriceRecord>(
    _entities[8].properties[2],
  );

  /// See [PriceRecord.recordedAt].
  static final recordedAt = obx.QueryDateProperty<PriceRecord>(
    _entities[8].properties[3],
  );

  /// See [PriceRecord.option].
  static final option = obx.QueryRelationToOne<PriceRecord, ComponentOption>(
    _entities[8].properties[4],
  );
}

/// [StockItem] entity fields to define ObjectBox queries.
class StockItem_ {
  /// See [StockItem.id].
  static final id = obx.QueryIntegerProperty<StockItem>(
    _entities[9].properties[0],
  );

  /// See [StockItem.quantity].
  static final quantity = obx.QueryIntegerProperty<StockItem>(
    _entities[9].properties[1],
  );

  /// See [StockItem.location].
  static final location = obx.QueryStringProperty<StockItem>(
    _entities[9].properties[2],
  );

  /// See [StockItem.variantJson].
  static final variantJson = obx.QueryStringProperty<StockItem>(
    _entities[9].properties[3],
  );

  /// See [StockItem.component].
  static final component = obx.QueryRelationToOne<StockItem, Component>(
    _entities[9].properties[4],
  );
}
