// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/entities/category.dart';
import 'model/entities/component.dart';
import 'model/entities/component_option.dart';
import 'model/entities/project.dart';
import 'model/entities/project_item.dart';
import 'model/entities/project_option.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 735688662067852918),
    name: 'Category',
    lastPropertyId: const obx_int.IdUid(5, 5065092297872908668),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8838519174728974467),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6716892446646810134),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5239876977356516614),
        name: 'colorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5065092297872908668),
        name: 'iconName',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'component',
        srcEntity: 'Component',
        srcField: 'category',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7432719125809346356),
    name: 'Component',
    lastPropertyId: const obx_int.IdUid(5, 6916872785050517054),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7873598098431675365),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3634271832066945026),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1915175074799785345),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1024023797232900842),
        name: 'base64Image',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6916872785050517054),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 267711657199906249),
        relationField: 'category',
        relationTarget: 'Category',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'options',
        srcEntity: 'ComponentOption',
        srcField: 'component',
      ),
      obx_int.ModelBacklink(
        name: 'projectItem',
        srcEntity: 'ProjectItem',
        srcField: 'component',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6081016848382265369),
    name: 'ComponentOption',
    lastPropertyId: const obx_int.IdUid(6, 1123915559444337),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3353291662892062929),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6390919814860314811),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 49313635525721526),
        name: 'unitsPerPack',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5973240023728994270),
        name: 'pricePerPack',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5092400232993980417),
        name: 'componentId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 5562498534427402224),
        relationField: 'component',
        relationTarget: 'Component',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'projectItem',
        srcEntity: 'ProjectItem',
        srcField: 'componentOption',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 4547103194667605335),
    name: 'ProjectItem',
    lastPropertyId: const obx_int.IdUid(8, 7113912605860092562),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7198949110572192655),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 877014537199689448),
        name: 'quantity',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 150656000289696912),
        name: 'componentId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 7914224584363898835),
        relationField: 'component',
        relationTarget: 'Component',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1956453245173252739),
        name: 'componentOptionId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(6, 6573140737730838987),
        relationField: 'componentOption',
        relationTarget: 'ComponentOption',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4349058352890504777),
        name: 'projectOptionId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(7, 2460496800844713591),
        relationField: 'projectOption',
        relationTarget: 'ProjectOption',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7113912605860092562),
        name: 'projectId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(8, 5632878586015758333),
        relationField: 'project',
        relationTarget: 'Project',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 371008579262511988),
    name: 'ProjectOption',
    lastPropertyId: const obx_int.IdUid(3, 5654727925094684581),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1501010626906604339),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8076127869418753446),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5654727925094684581),
        name: 'projectId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(9, 3612696205726049625),
        relationField: 'project',
        relationTarget: 'Project',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'items',
        srcEntity: 'ProjectItem',
        srcField: 'projectOption',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 8436796991232977367),
    name: 'Project',
    lastPropertyId: const obx_int.IdUid(2, 3772008035074211062),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7550198771448469810),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3772008035074211062),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 2185989689109593573),
        name: 'projectOptions',
        targetId: const obx_int.IdUid(5, 371008579262511988),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'baseItems',
        srcEntity: 'ProjectItem',
        srcField: 'project',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 8436796991232977367),
    lastIndexId: const obx_int.IdUid(9, 3612696205726049625),
    lastRelationId: const obx_int.IdUid(2, 2185989689109593573),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [7121405856924190099, 7543092616379739934],
    retiredPropertyUids: const [
      5724160405490332509,
      932998436461860071,
      8919251242098379596,
      1123915559444337,
    ],
    retiredRelationUids: const [4042897894924188460],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Category: obx_int.EntityDefinition<Category>(
      model: _entities[0],
      toOneRelations: (Category object) => [],
      toManyRelations: (Category object) => {
        obx_int.RelInfo<Component>.toOneBacklink(
          5,
          object.id,
          (Component srcObject) => srcObject.category,
        ): object.component,
      },
      getId: (Category object) => object.id,
      setId: (Category object, int id) {
        object.id = id;
      },
      objectToFB: (Category object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final iconNameOffset = fbb.writeString(object.iconName);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(3, object.colorValue);
        fbb.addOffset(4, iconNameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final colorValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final iconNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = Category(
          id: idParam,
          name: nameParam,
          colorValue: colorValueParam,
          iconName: iconNameParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<Category>(
          object.component,
          store,
          obx_int.RelInfo<Component>.toOneBacklink(
            5,
            object.id,
            (Component srcObject) => srcObject.category,
          ),
        );
        return object;
      },
    ),
    Component: obx_int.EntityDefinition<Component>(
      model: _entities[1],
      toOneRelations: (Component object) => [object.category],
      toManyRelations: (Component object) => {
        obx_int.RelInfo<ComponentOption>.toOneBacklink(
          5,
          object.id,
          (ComponentOption srcObject) => srcObject.component,
        ): object.options,
        obx_int.RelInfo<ProjectItem>.toOneBacklink(
          3,
          object.id,
          (ProjectItem srcObject) => srcObject.component,
        ): object.projectItem,
      },
      getId: (Component object) => object.id,
      setId: (Component object, int id) {
        object.id = id;
      },
      objectToFB: (Component object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final base64ImageOffset = fbb.writeString(object.base64Image);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, base64ImageOffset);
        fbb.addInt64(4, object.category.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final base64ImageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = Component(
          id: idParam,
          name: nameParam,
          description: descriptionParam,
          base64Image: base64ImageParam,
        );
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.category.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Component>(
          object.options,
          store,
          obx_int.RelInfo<ComponentOption>.toOneBacklink(
            5,
            object.id,
            (ComponentOption srcObject) => srcObject.component,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Component>(
          object.projectItem,
          store,
          obx_int.RelInfo<ProjectItem>.toOneBacklink(
            3,
            object.id,
            (ProjectItem srcObject) => srcObject.component,
          ),
        );
        return object;
      },
    ),
    ComponentOption: obx_int.EntityDefinition<ComponentOption>(
      model: _entities[2],
      toOneRelations: (ComponentOption object) => [object.component],
      toManyRelations: (ComponentOption object) => {
        obx_int.RelInfo<ProjectItem>.toOneBacklink(
          6,
          object.id,
          (ProjectItem srcObject) => srcObject.componentOption,
        ): object.projectItem,
      },
      getId: (ComponentOption object) => object.id,
      setId: (ComponentOption object, int id) {
        object.id = id;
      },
      objectToFB: (ComponentOption object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.unitsPerPack);
        fbb.addFloat64(3, object.pricePerPack);
        fbb.addInt64(4, object.component.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final unitsPerPackParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final pricePerPackParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = ComponentOption(
          id: idParam,
          name: nameParam,
          unitsPerPack: unitsPerPackParam,
          pricePerPack: pricePerPackParam,
        );
        object.component.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.component.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<ComponentOption>(
          object.projectItem,
          store,
          obx_int.RelInfo<ProjectItem>.toOneBacklink(
            6,
            object.id,
            (ProjectItem srcObject) => srcObject.componentOption,
          ),
        );
        return object;
      },
    ),
    ProjectItem: obx_int.EntityDefinition<ProjectItem>(
      model: _entities[3],
      toOneRelations: (ProjectItem object) => [
        object.component,
        object.componentOption,
        object.projectOption,
        object.project,
      ],
      toManyRelations: (ProjectItem object) => {},
      getId: (ProjectItem object) => object.id,
      setId: (ProjectItem object, int id) {
        object.id = id;
      },
      objectToFB: (ProjectItem object, fb.Builder fbb) {
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.quantity);
        fbb.addInt64(2, object.component.targetId);
        fbb.addInt64(5, object.componentOption.targetId);
        fbb.addInt64(6, object.projectOption.targetId);
        fbb.addInt64(7, object.project.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final quantityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final object = ProjectItem(id: idParam, quantity: quantityParam);
        object.component.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.component.attach(store);
        object.componentOption.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        object.componentOption.attach(store);
        object.projectOption.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.projectOption.attach(store);
        object.project.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        object.project.attach(store);
        return object;
      },
    ),
    ProjectOption: obx_int.EntityDefinition<ProjectOption>(
      model: _entities[4],
      toOneRelations: (ProjectOption object) => [object.project],
      toManyRelations: (ProjectOption object) => {
        obx_int.RelInfo<ProjectItem>.toOneBacklink(
          7,
          object.id,
          (ProjectItem srcObject) => srcObject.projectOption,
        ): object.items,
      },
      getId: (ProjectOption object) => object.id,
      setId: (ProjectOption object, int id) {
        object.id = id;
      },
      objectToFB: (ProjectOption object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.project.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = ProjectOption(id: idParam, name: nameParam);
        object.project.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.project.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<ProjectOption>(
          object.items,
          store,
          obx_int.RelInfo<ProjectItem>.toOneBacklink(
            7,
            object.id,
            (ProjectItem srcObject) => srcObject.projectOption,
          ),
        );
        return object;
      },
    ),
    Project: obx_int.EntityDefinition<Project>(
      model: _entities[5],
      toOneRelations: (Project object) => [],
      toManyRelations: (Project object) => {
        obx_int.RelInfo<Project>.toMany(2, object.id): object.projectOptions,
        obx_int.RelInfo<ProjectItem>.toOneBacklink(
          8,
          object.id,
          (ProjectItem srcObject) => srcObject.project,
        ): object.baseItems,
      },
      getId: (Project object) => object.id,
      setId: (Project object, int id) {
        object.id = id;
      },
      objectToFB: (Project object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = Project(id: idParam, name: nameParam);
        obx_int.InternalToManyAccess.setRelInfo<Project>(
          object.projectOptions,
          store,
          obx_int.RelInfo<Project>.toMany(2, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<Project>(
          object.baseItems,
          store,
          obx_int.RelInfo<ProjectItem>.toOneBacklink(
            8,
            object.id,
            (ProjectItem srcObject) => srcObject.project,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Category] entity fields to define ObjectBox queries.
class Category_ {
  /// See [Category.id].
  static final id = obx.QueryIntegerProperty<Category>(
    _entities[0].properties[0],
  );

  /// See [Category.name].
  static final name = obx.QueryStringProperty<Category>(
    _entities[0].properties[1],
  );

  /// See [Category.colorValue].
  static final colorValue = obx.QueryIntegerProperty<Category>(
    _entities[0].properties[2],
  );

  /// See [Category.iconName].
  static final iconName = obx.QueryStringProperty<Category>(
    _entities[0].properties[3],
  );

  /// see [Category.component]
  static final component = obx.QueryBacklinkToMany<Component, Category>(
    Component_.category,
  );
}

/// [Component] entity fields to define ObjectBox queries.
class Component_ {
  /// See [Component.id].
  static final id = obx.QueryIntegerProperty<Component>(
    _entities[1].properties[0],
  );

  /// See [Component.name].
  static final name = obx.QueryStringProperty<Component>(
    _entities[1].properties[1],
  );

  /// See [Component.description].
  static final description = obx.QueryStringProperty<Component>(
    _entities[1].properties[2],
  );

  /// See [Component.base64Image].
  static final base64Image = obx.QueryStringProperty<Component>(
    _entities[1].properties[3],
  );

  /// See [Component.category].
  static final category = obx.QueryRelationToOne<Component, Category>(
    _entities[1].properties[4],
  );

  /// see [Component.options]
  static final options = obx.QueryBacklinkToMany<ComponentOption, Component>(
    ComponentOption_.component,
  );

  /// see [Component.projectItem]
  static final projectItem = obx.QueryBacklinkToMany<ProjectItem, Component>(
    ProjectItem_.component,
  );
}

/// [ComponentOption] entity fields to define ObjectBox queries.
class ComponentOption_ {
  /// See [ComponentOption.id].
  static final id = obx.QueryIntegerProperty<ComponentOption>(
    _entities[2].properties[0],
  );

  /// See [ComponentOption.name].
  static final name = obx.QueryStringProperty<ComponentOption>(
    _entities[2].properties[1],
  );

  /// See [ComponentOption.unitsPerPack].
  static final unitsPerPack = obx.QueryIntegerProperty<ComponentOption>(
    _entities[2].properties[2],
  );

  /// See [ComponentOption.pricePerPack].
  static final pricePerPack = obx.QueryDoubleProperty<ComponentOption>(
    _entities[2].properties[3],
  );

  /// See [ComponentOption.component].
  static final component = obx.QueryRelationToOne<ComponentOption, Component>(
    _entities[2].properties[4],
  );

  /// see [ComponentOption.projectItem]
  static final projectItem =
      obx.QueryBacklinkToMany<ProjectItem, ComponentOption>(
        ProjectItem_.componentOption,
      );
}

/// [ProjectItem] entity fields to define ObjectBox queries.
class ProjectItem_ {
  /// See [ProjectItem.id].
  static final id = obx.QueryIntegerProperty<ProjectItem>(
    _entities[3].properties[0],
  );

  /// See [ProjectItem.quantity].
  static final quantity = obx.QueryIntegerProperty<ProjectItem>(
    _entities[3].properties[1],
  );

  /// See [ProjectItem.component].
  static final component = obx.QueryRelationToOne<ProjectItem, Component>(
    _entities[3].properties[2],
  );

  /// See [ProjectItem.componentOption].
  static final componentOption =
      obx.QueryRelationToOne<ProjectItem, ComponentOption>(
        _entities[3].properties[3],
      );

  /// See [ProjectItem.projectOption].
  static final projectOption =
      obx.QueryRelationToOne<ProjectItem, ProjectOption>(
        _entities[3].properties[4],
      );

  /// See [ProjectItem.project].
  static final project = obx.QueryRelationToOne<ProjectItem, Project>(
    _entities[3].properties[5],
  );
}

/// [ProjectOption] entity fields to define ObjectBox queries.
class ProjectOption_ {
  /// See [ProjectOption.id].
  static final id = obx.QueryIntegerProperty<ProjectOption>(
    _entities[4].properties[0],
  );

  /// See [ProjectOption.name].
  static final name = obx.QueryStringProperty<ProjectOption>(
    _entities[4].properties[1],
  );

  /// See [ProjectOption.project].
  static final project = obx.QueryRelationToOne<ProjectOption, Project>(
    _entities[4].properties[2],
  );

  /// see [ProjectOption.items]
  static final items = obx.QueryBacklinkToMany<ProjectItem, ProjectOption>(
    ProjectItem_.projectOption,
  );
}

/// [Project] entity fields to define ObjectBox queries.
class Project_ {
  /// See [Project.id].
  static final id = obx.QueryIntegerProperty<Project>(
    _entities[5].properties[0],
  );

  /// See [Project.name].
  static final name = obx.QueryStringProperty<Project>(
    _entities[5].properties[1],
  );

  /// see [Project.projectOptions]
  static final projectOptions = obx.QueryRelationToMany<Project, ProjectOption>(
    _entities[5].relations[0],
  );

  /// see [Project.baseItems]
  static final baseItems = obx.QueryBacklinkToMany<ProjectItem, Project>(
    ProjectItem_.project,
  );
}
